<Project>
  <Import Project="..\Version.props" />
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="TUnit" Version="1.66.27" />
    <PackageVersion Include="IconifyBundle" Version="$(IconifyBundleVersion)" />
    <PackageVersion Include="IconifyBundle.Feather" Version="$(IconifyBundleVersion)" />
  </ItemGroup>
</Project>
